# Generated by Django 4.0.5 on 2022-06-05 09:54

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lock',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='nearyby',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='phase',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='lock',
            name='area',
            field=models.FloatField(verbose_name='ขนาด(ตร.วา)'),
        ),
        migrations.AlterField(
            model_name='lock',
            name='description',
            field=models.TextField(max_length=255, verbose_name='รายละเอียด'),
        ),
        migrations.AlterField(
            model_name='lock',
            name='location',
            field=models.URLField(max_length=100, verbose_name='ที่อยู่'),
        ),
        migrations.AlterField(
            model_name='lock',
            name='monthly',
            field=models.FloatField(verbose_name='ราคา/เดือน(ไม่ต้องใส่ ,)'),
        ),
        migrations.AlterField(
            model_name='lock',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ขื่อล๊อก'),
        ),
        migrations.AlterField(
            model_name='lock',
            name='phase',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='phase_lock', to='api.phase', verbose_name='ขื่อเฟส'),
        ),
        migrations.AlterField(
            model_name='lock',
            name='price',
            field=models.IntegerField(verbose_name='ราคา(ไม่หน่อยใส่ ,)'),
        ),
        migrations.AlterField(
            model_name='lock',
            name='videoNearby',
            field=models.CharField(max_length=100, verbose_name='วิดิโอสถานที่ใกล้เคียง'),
        ),
        migrations.AlterField(
            model_name='lock',
            name='videoView',
            field=models.CharField(max_length=100, verbose_name='วิดิโอบรรยากาศ'),
        ),
        migrations.AlterField(
            model_name='lockimage',
            name='image',
            field=models.ImageField(upload_to=api.models.LockImage.get_image_filename, verbose_name='รูปภาพในล็อก'),
        ),
        migrations.AlterField(
            model_name='lockimage',
            name='lock',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.lock', verbose_name='ขื่อล็อก'),
        ),
        migrations.AlterField(
            model_name='nearyby',
            name='description',
            field=models.TextField(max_length=255, verbose_name='รายละเอียด'),
        ),
        migrations.AlterField(
            model_name='nearyby',
            name='distance',
            field=models.CharField(max_length=100, verbose_name='ระยะทาง'),
        ),
        migrations.AlterField(
            model_name='nearyby',
            name='link',
            field=models.URLField(blank=True, max_length=100, verbose_name='ลิงก์(ถ้ามี) '),
        ),
        migrations.AlterField(
            model_name='nearyby',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ขื่อสถานที่'),
        ),
        migrations.AlterField(
            model_name='nearyby',
            name='phase',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='nearbies', to='api.phase', verbose_name='ขื่อเฟส'),
        ),
        migrations.AlterField(
            model_name='nearyby',
            name='time',
            field=models.CharField(max_length=100, verbose_name='เวลาคาดการณ์'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='description',
            field=models.TextField(max_length=255, verbose_name='รายละเอียด'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='layoutImage',
            field=models.ImageField(upload_to=api.models.Phase.get_image_filename, verbose_name='ภาพแผนผังที่ดิน'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='location',
            field=models.URLField(max_length=100, verbose_name='ที่อยู่(ลิงก์)'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ขื่อเฟส'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='videoHealth',
            field=models.CharField(blank=True, max_length=100, verbose_name='วิดิโอสาธารณูปโภค(ถ้ามี)'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='videoNearby',
            field=models.CharField(max_length=100, verbose_name='วิดิโอสถานที่ใกล้เคียง'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='videoView',
            field=models.CharField(max_length=100, verbose_name='วิดิโอบรรยากาศ'),
        ),
        migrations.AlterField(
            model_name='phaseimage',
            name='image',
            field=models.ImageField(upload_to=api.models.PhaseImage.get_image_filename, verbose_name='รูปภาพเฟส'),
        ),
        migrations.AlterField(
            model_name='phaseimage',
            name='phase',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.phase', verbose_name='ขื่อเฟส'),
        ),
    ]
