# Generated by Django 4.0.5 on 2022-06-19 09:27

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_lock_options_alter_nearyby_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='layoutImage',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='videoHealth',
        ),
        migrations.AlterField(
            model_name='phaseimage',
            name='phase',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='phase_images', to='api.phase', verbose_name='ขื่อเฟส'),
        ),
        migrations.CreateModel(
            name='LayoutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.LayoutImage.get_image_filename, verbose_name='รูปภาพแผนผังเฟส')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('phase', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='layout_images', to='api.phase', verbose_name='ขื่อเฟส')),
            ],
        ),
    ]
