# Generated by Django 4.0.5 on 2022-06-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_phase_layoutimage_remove_phase_videohealth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lock',
            name='health_description',
            field=models.TextField(max_length=255, null=True, verbose_name='รายละเอียดสาธานูปโภค'),
        ),
    ]
