# Generated by Django 4.0.5 on 2022-06-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_lock_health_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lock',
            name='health_description',
        ),
        migrations.AddField(
            model_name='phase',
            name='health_description',
            field=models.TextField(max_length=255, null=True, verbose_name='รายละเอียดสาธานูปโภค'),
        ),
    ]
